image: java_builder_docker_java12

matrix:
  - env: SCRIPT=test

before_script:
  - docker login registry.kloud.software -u $DOCKER_USER -p $DOCKER_PASS
  - docker-compose up -d
  - echo $(pwd)
  - mkdir tmpPlugin
  - 'cd tmpPlugin && git clone https://github.com/kloud-ms/kms-sample-plugin.git && cd kms-sample-plugin && ./gradlew build -x test && mv build/libs/* ../../plugins'
script:
  - ./gradlew $SCRIPT --stacktrace
after_script:
  - docker-compose down
after_successful:
  - docker-compose down
after_failure:
  - docker-compose down
