image: java_builder_docker_java12

matrix:
  - env: SCRIPT=bootJar

before_script:
  - docker login registry.kloud.software -u $DOCKER_USER -p $DOCKER_PASS
  - docker-compose up -d
  - mkdir tmpPlugin
  - cd tmpPlugin
  - git clone https://github.com/kloud-ms/kms-sample-plugin.git
  - cd kms-sample-plugin
  - ./gradlew build
  - mv build/libs/* ../../plugins
script:
  - ./gradlew $SCRIPT