image: abstruse_builder

matrix:
  - env: TEXT=howdy
  - env: TEXT=hello

branches:
  test:
    - master
before-install:
  - apt-get -yqq update
install:
  - apt-get install -yqq cowsay
script:
  - cowsay $TEXT