version: "3"

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: kloudfile
      MYSQL_DATABASE: kms
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/cnf:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
  silver:
    image: registry.kloud.software/silver-fork
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource": {"url": "jdbc:mysql://db:3306/kms?useSSL=false", "password": "kloudfile"},
            "redis": {"host": "redis", "port": 6380}}'
    ports:
      - 8081:8081
    links:
      - db:db
      - redis:redis
  redis:
    image: redis:latest
    ports:
    - 6380:6379
